import {
  Activity,
  ArrowBigUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Bell,
  BellOff,
  BookOpen,
  Box,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clock,
  CloudUpload,
  Code,
  CodeXml,
  Copy,
  CornerDownRight,
  CornerUpLeft,
  Cpu,
  Delete,
  Ellipsis,
  ExternalLink,
  EyeOff,
  Feather,
  File,
  FileText,
  Film,
  Flag,
  FolderGit2,
  GitBranch,
  GitPullRequest,
  Globe,
  HardDrive,
  Heart,
  House,
  Image,
  Inbox,
  Languages,
  Lightbulb,
  Link,
  List,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Moon,
  Paperclip,
  PenLine,
  Pencil,
  Phone,
  Play,
  Plus,
  Radio,
  RefreshCcw,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShieldOff,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  SquarePlus,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  UserRound,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
} from 'lucide-react-native';

/**
 * Noms d'icônes de l'app (hérités de Feather) → icônes Lucide, les mêmes que sur le web.
 * Import nommé : seules ces icônes sont embarquées.
 */
export const LUCIDE: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': TriangleAlert,
  'arrow-big-up': ArrowBigUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  'bar-chart-2': ChartColumn,
  bell: Bell,
  'bell-off': BellOff,
  'book-open': BookOpen,
  box: Box,
  calendar: Calendar,
  check: Check,
  'check-circle': CircleCheck,
  'check-square': SquareCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  clock: Clock,
  code: Code,
  'code-xml': CodeXml,
  copy: Copy,
  'corner-down-right': CornerDownRight,
  'corner-up-left': CornerUpLeft,
  cpu: Cpu,
  delete: Delete,
  'edit-2': Pencil,
  'edit-3': PenLine,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  feather: Feather,
  file: File,
  'file-text': FileText,
  film: Film,
  flag: Flag,
  'folder-git': FolderGit2,
  'git-branch': GitBranch,
  'git-pull-request': GitPullRequest,
  globe: Globe,
  'hard-drive': HardDrive,
  heart: Heart,
  'help-circle': CircleHelp,
  home: House,
  image: Image,
  inbox: Inbox,
  languages: Languages,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  mic: Mic,
  moon: Moon,
  'more-horizontal': Ellipsis,
  paperclip: Paperclip,
  phone: Phone,
  play: Play,
  plus: Plus,
  'plus-square': SquarePlus,
  radio: Radio,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  smartphone: Smartphone,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  tool: Wrench,
  'trash-2': Trash2,
  'upload-cloud': CloudUpload,
  user: User,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  video: Video,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  'x-circle': CircleX,
  zap: Zap,
};
